name = "SlicedNormals"
uuid = "78bc189a-7b6d-4df1-8a23-377b7c6fd0cb"
authors = ["Jasper Behrensdorf <behrensdorf@irz.uni-hannover.de>"]
version = "0.1.0"

[deps]
CovarianceEstimation = "587fd27a-f159-11e8-2dae-1979310e6154"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
HCubature = "19dc6840-f33b-545b-b366-655c7e3ffd49"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Memoize = "c03570c3-d221-55d1-a50c-7939bbd78826"
PDMats = "90014a1f-27ba-587c-ab20-58faa44d9150"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TransitionalMCMC = "5bc637a6-1a46-43ed-8ea7-ee39cc1921ce"
